.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoincloud_qt test_bitcoincloud_qt
clean: FORCE
	$(MAKE) -C .. bitcoincloud_qt_clean test_bitcoincloud_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoincloud_qt_check
bitcoincloud-qt bitcoincloud-qt.exe: FORCE
	 $(MAKE) -C .. bitcoincloud_qt
